WebFrontControllerのコンポーネント名を動的に取得するように修正
nablarch/nablarch-fw-web pull request #106
Opened 2023-02-07 01:05 UTC by takikunxo

2023-02-07 06:07 UTC, kumagoro1202 requested changes

2023-02-07 06:07 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> +        String componentName = filterConfig.getInitParameter("component-name");
componentNameだと対象がわかりにくいので、controllerNameの方がより良いです。

2023-02-07 06:07 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/WebFrontController.java
> + *     &lt;/init-param>
このパラメータはRepositoryBasedWebFrontControllerに対するパラメータです。WebFrontControllerに対して設定しても無視されるので、書くべきはここではなくRepositoryBasedWebFrontControllerのJavadocです。

2023-02-07 06:07 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> +        String componentName = filterConfig.getInitParameter("component-name");
クラスのJavadocにデフォルトではwebFrontControllerという名前で移譲するWebFrontControllerを取得することと、<init-param>で名前を変更できることを追記してください。

2023-02-07 06:07 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +     */
この説明だと何のためのテストかが読み取りにくいです。

- デフォルト値と異なる値をinit-paramに設定すると移譲されるWebFrontControllerは指定した名前のものであること
- デフォルト値の名前で定義されたwebFrontControllerは使われないこと

をテストして欲しいです。

2023-02-07 06:07 UTC, kumagoro1202 commented on src/test/resources/nablarch/fw/web/servlet/repository-based-web-front-controller-specific-test.xml
> +    <component name="specificController"
デフォルトの名前のwebFrontControllerも定義し、そちらが使われないことをテストしてください。

2023-02-07 06:07 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +                    return "specificController";
好みの問題もありますが、specificControllerという名前よりotherNameControllerの方がテスト内容がわかりやすいかなと思いました。

2023-02-07 08:50 UTC, takikunxo commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> +        String componentName = filterConfig.getInitParameter("component-name");
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/838e605e555d9527493d80838bee24c0a3e56d87)のコミットにて修正しました。

2023-02-07 08:51 UTC, takikunxo commented on src/main/java/nablarch/fw/web/servlet/WebFrontController.java
> + *     &lt;/init-param>
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/b62cccc63cd803bb94388b1d660fef77427cb10b)のコミットにてRevertしました。

2023-02-07 08:52 UTC, takikunxo commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> +        String componentName = filterConfig.getInitParameter("component-name");
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/f3562e9f52b39d8c3a417dae8f6230b6b80a6014)のコミットにて説明を追記しました。

2023-02-07 08:54 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +     */
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/c3736d4c87b3c1ef883c046748c4af918a3c121c)のコミットにて単体テスト観点を修正しました。

2023-02-07 08:55 UTC, takikunxo commented on src/test/resources/nablarch/fw/web/servlet/repository-based-web-front-controller-specific-test.xml
> +    <component name="specificController"
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/89522066c4b16f3658332954a07d15e1450e5b65)のコミットにてwebFrontControllerの定義も追加しました。

2023-02-07 08:56 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +                    return "specificController";
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/89522066c4b16f3658332954a07d15e1450e5b65)のコミットにてotherNameControllerに名前を変更しました。

2023-02-08 02:10 UTC, takikunxo commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> +        String componentName = filterConfig.getInitParameter("component-name");
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/71e10a30a139091b92485fe562cb2b069c5e81a2)でgetInitParameterで使用していた、component-nameもcontrollerNameに修正しました。

2023-02-08 02:11 UTC, takikunxo commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> +        String componentName = filterConfig.getInitParameter("component-name");
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/bdf9255db0861841270825d2b2587559639a0468)でJavadocの記載方法追加で修正しました。

2023-02-08 02:12 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +     */
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/ab8780b5d8c6a5bfce6485971939aec7856f817b)で単体テストでJMockitなどを使うよう修正追加しております。

2023-02-08 03:06 UTC, kumagoro1202 requested changes

2023-02-08 03:06 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> + *
この文章は整形済みテキストである必要はないので`<pre>`は不要だと思います。

2023-02-08 03:06 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> + *
現状の記述でJavadoc生成すると以下のようになります。
![image](https://user-images.githubusercontent.com/58413950/217414572-ff66a57a-224a-479c-964c-34eda421af14.png)

意味的には最初の4行が説明の文章で、「デプロイメントディスクリプタの記述例」から下がコード例だと思うので、以下のようにするのがいいかと思いました。

```
/**
 * リポジトリ機能を使用して構築した{@link WebFrontController}を保持し、
 * そこに対してリクエスト処理を委譲するリクエストコントローラー.<br>
 * controllerNameのパラメータ値にコントローラ名を設定することで、設定した名前を元に移譲するWebFrontControllerを取得することができる。
 * デフォルトではwebFrontControllerという名前で移譲するWebFrontControllerを取得する。
 * <pre>{@code
 * -------------------------------------
 * デプロイメントディスクリプタの記述例
 * -------------------------------------
 * <?xml version="1.0" encoding="UTF-8"?>
 * <web-app xmlns="http://java.sun.com/xml/ns/javaee"
 *          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 *          xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
 *          version="2.5">
 *   <display-name>w8</display-name>
 *   <description>
```

これをJavadoc生成すると以下のようになります。
![image](https://user-images.githubusercontent.com/58413950/217414893-aefe11df-f847-49ce-ba84-aa1454bdcfb8.png)

2023-02-08 03:06 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +            public String getInitParameter(String arg0) {
引数の変数名はarg0という名前ではなく、[FilterConfigのソース同様](https://spring.pleiades.io/specifications/platform/8/apidocs/javax/servlet/filterconfig#getInitParameter-java.lang.String-)`name`とするのがいいと思います。

2023-02-08 03:06 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +                if (arg0=="controllerName"){
JavaでStringの比較を行うときは[equalsメソッド](https://docs.oracle.com/javase/jp/8/docs/api/java/lang/String.html#equals-java.lang.Object-)を使うようにしてください。

2023-02-08 03:06 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +    }
インスタンスの比較を行うためのassertSameというメソッドがあるのでそちらを使ってもらった方がいいかと思います。

```
        assertNotSame(defaultWebController, actualWebController);
        assertSame(expectedWebController, actualWebController);
```

2023-02-08 03:06 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +    public void testOtherNameWebFrontControllerOnRepository() throws ServletException, IOException {
このテストコードではIOExceptionは発生しないので削除してください。

2023-02-08 03:06 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> + *
こうするイメージ
https://github.com/nablarch/nablarch-fw-web/commit/247e5250e55803f0ef2a02eaf7ae307e8fcea452

2023-02-08 03:06 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +            public String getInitParameter(String arg0) {
既存テストコードも含め無名クラスを3回宣言するよりテスト用に実装クラス作ったほうがスッキリすると思いました。
こんな感じでどうでしょう。
https://github.com/nablarch/nablarch-fw-web/commit/535c3ec03a4da1287d843ee33cb3ad785604bd99

2023-02-08 03:06 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +                if (arg0=="controllerName"){
テスト用のクラスを作るならこの指摘は取り下げます。

2023-02-08 05:01 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +    }
比較のしかた自体は変わらなそうですが、テスト失敗時のエラーのわかりやすさが違いそうですね！

2023-02-08 05:16 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +                if (arg0=="controllerName"){
テスト用のクラス作成の方を採用させていただきます。

2023-02-08 05:31 UTC, takikunxo commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> + *
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/1fad40c218c7188284ac50820c720f08d8fce7c5)にて修正しました。
[WebFrontController.java](https://nablarch.github.io/docs/5u10/javadoc/nablarch/fw/web/servlet/WebFrontController.html)の方に揃えてましたが
こちらは段落揃えたいという意図があっての<pre>タグでしたね。

2023-02-08 05:32 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +            public String getInitParameter(String arg0) {
ありがとうございます。[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/11fbd343f3fc804c052d8b7a50534382a59bdf71)にて採用させていただきました。

2023-02-08 05:32 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +    }
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/93c1e50b4ca15c412c67e0af7d2ddc4f0704af11)にて修正しました。

2023-02-08 05:32 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +    public void testOtherNameWebFrontControllerOnRepository() throws ServletException, IOException {
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/cd8296bef620238d39b7a574fceed275c808dde2)にて修正しました。

2023-02-08 05:55 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontController.java
> + *
そうですね。WebFrontControllerの方は本来なら`<ol>`タグを使うなどして箇条書きを表現するべきですが`<pre>`タグを使って無理やり実現していますね。。

2023-02-08 05:57 UTC, kumagoro1202 requested changes

2023-02-08 05:57 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +import java.lang.reflect.Field;
不要なimportが残ってしまっています。

2023-02-08 10:31 UTC, takikunxo commented on src/test/java/nablarch/fw/web/servlet/RepositoryBasedWebFrontControllerTest.java
> +import java.lang.reflect.Field;
すみません、確認漏れです。
[こちら](https://github.com/nablarch/nablarch-fw-web/pull/106/commits/7e5a1b105d2ec26f9eddf8411e988b65f1f69da6)で修正しました。

2023-02-08 23:58 UTC, kumagoro1202 approved these changes

2023-02-08 23:58 UTC, merged