Jakarta EE 対応
nablarch/nablarch-fw-web pull request #110
Opened 2023-02-17 11:30 UTC by opengl-8080

jetty を切り替える仕組みの土台となる部分は、将来また複数 jetty を切り替える必要性が生じたときのために残しています。
ただし、`env.additional-test-source`が必要になるのは、 Servlet のバージョンが上がった時に非互換の仕様変更があるかどうか次第であり、 jetty を複数バージョンで切り替えるようになっても絶対必要になるとは限らないものなので、ひとまず削除してます。

複数 Jetty でテストを動かすことを前提に、特定のバージョンでだけテストを動かすようにしていたものは、全て一本に統一しました。

`ServletExecutionContextTest.java` で判定のロジックを変更しているのは、スコープに入っているエントリの数がバージョンアップで変わりエラーになるようになったためです。
エントリの数を絶対数で判定していると今後も同様の理由でエラーになりかねないので、相対数で判定するようにしました。

2023-02-21 08:34 UTC, kumagoro1202 requested changes

2023-02-21 08:34 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/servlet/UriUtil.java
> +            // Jakarta Servlet Specification 6.0.0 9.4.2. Forwarded Request Parameters
Java Servlet Specificationのコメントは消しちゃっていいのではと思いました。

2023-02-22 04:46 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/servlet/UriUtil.java
> +            // Jakarta Servlet Specification 6.0.0 9.4.2. Forwarded Request Parameters
https://github.com/nablarch/nablarch-fw-web/pull/110/commits/0e92dd18996b8e990004c2633666b39b5376fb48
削除しました

2023-02-22 08:15 UTC, kumagoro1202 approved these changes

2023-02-22 08:15 UTC, merged