Nab 530/parse multi cookies
nablarch/nablarch-fw-web pull request #117
Opened 2023-05-24 00:48 UTC by chupaaaaaaan

2023-05-25 06:16 UTC, kumagoro1202 requested changes

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +     * @return　{@link HttpCookie}オブジェクト
`@return`の後ろに全角スペースが入っているのでJavadocが壊れています。

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +    static HttpCookie convertHttpCookie(Cookie cookie) {
factoryメソッドなのでconvertは違和感があります。

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +     * 本メソッドでは、Path、Domain、Max-Age、Secure、HttpOnly属性のみをサポートし、不適切な属性は無視する。
不適切な属性というのは不適切。

2023-05-25 06:16 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        String[] cookiePair = cookieTokens[0].trim().split("=");
値には`=`が入り得るのでsplitはまずい。

2023-06-01 05:16 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +     * @return　{@link HttpCookie}オブジェクト
修正しました。

2023-06-01 05:22 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +    static HttpCookie convertHttpCookie(Cookie cookie) {
fromServletCookieに修正しました。
合わせて、parseSetCookieもfromSetCookieHeaderに変更しました。

2023-06-01 05:23 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +     * 本メソッドでは、Path、Domain、Max-Age、Secure、HttpOnly属性のみをサポートし、不適切な属性は無視する。
記載を修正しました。

2023-06-01 05:24 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        String[] cookiePair = cookieTokens[0].trim().split("=");
split(regex, limit)を使用して書きなおしました。

2023-06-01 08:33 UTC, kumagoro1202 requested changes

2023-06-01 08:33 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        }
`seCookie.get(0)`を変数に入れましょう。

2023-06-01 08:33 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        // JavaEEのCookieクラスでは、Max-Age属性の値をint型で保持しているため、Long型の値をint型にキャストしている。
HttpCookieがJavaEEのCookieクラスに合わせてIntegerで保持していることを書かないと何で急に関係ないJavaEEの話を始めたんだろうという感想になります。

2023-06-01 08:33 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        if(httpCookie.supportsHttpOnly()) {
何のためにこの判定をしていますか？

2023-06-01 09:01 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        }
修正しました。

2023-06-01 09:05 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        // JavaEEのCookieクラスでは、Max-Age属性の値をint型で保持しているため、Long型の値をint型にキャストしている。
すみません、自分でも読み直して意味が通らないことに気が付きました。

seCookie.getMaxAge()の型もLongではなくlongであるので、それも含めて修正しました。

2023-06-01 09:15 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        if(httpCookie.supportsHttpOnly()) {
HttpOnly属性をサポートしていないservletの場合、後続の`httpCookie.setHttpOnly()`が`UnsupportedOperationException`を送出するためです。
（Jetty6で実行すると再現します）

2023-06-02 01:02 UTC, kumagoro1202 requested changes

2023-06-02 01:02 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        List<java.net.HttpCookie> seCookies = java.net.HttpCookie.parse(header);
seCookiesという名前はどういう意味でしょうか。seが何を指すのかわからず。

2023-06-02 01:20 UTC, kumagoro1202 requested changes

2023-06-02 01:20 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/HttpCookieTest.java
> +        assertTrue(cookie.getDelegateMap().containsKey("cookie"));
MapWrapperはMapのメソッドをオーバーライドしてるのでgetDelegateMapしなくても直接containsKeyメソッドを呼べます。ほかも同様。

2023-06-02 01:20 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/HttpCookieTest.java
> +    }
Set-Cookieヘッダで"="の前後にスペースが入っているパターンもテストしましょう。
どういうことができるかを宣言する意味で。

2023-06-02 01:20 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        HttpCookie cookie00 = new HttpCookie(); cookie00.getDelegateMap().put("cookie00", "value00"); res.addCookie(cookie00);
こっちもgetDelegateMapは不要。

2023-06-02 05:41 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +        List<java.net.HttpCookie> seCookies = java.net.HttpCookie.parse(header);
JavaSEで提供しているCookieの意図でした。
サーブレットのCookieと紛らわしいかと思いseを付けましたが、本メソッドではサーブレットのCookieを使用しておらず、混乱の可能性は少ないとしてcookiesという名前に変更しました。

2023-06-02 05:41 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/web/HttpCookieTest.java
> +        assertTrue(cookie.getDelegateMap().containsKey("cookie"));
修正しました。

2023-06-02 05:44 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/web/HttpCookieTest.java
> +    }
クッキー名・クッキー値・属性名・属性値それぞれの前後に空白が入っているパターンのテストを追加しました。

2023-06-02 06:13 UTC, kumagoro1202 requested changes

2023-06-02 06:13 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        HttpCookie cookie04 = new HttpCookie(); cookie04.put("cookie04", "value04"); cookie04.setSecure(true); res.addCookie(cookie04);
１つの行にセミコロンは１つとした方が読みやすいです。
1行で書きたいならBuilderパターンにするのもありかと思いました。

2023-06-02 06:13 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +            }
サーブレットCookieの設定が個別に違っている場合にそれぞれ設定した値だけがセットされていることを確認するなら、他の属性に値がセットされていないことも確認した方がいいと思います。

2023-06-05 05:54 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        HttpCookie cookie04 = new HttpCookie(); cookie04.put("cookie04", "value04"); cookie04.setSecure(true); res.addCookie(cookie04);
builderパターンで書き直しました。

2023-06-05 06:01 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +            }
他の属性に値がセットされていない確認を追加しました。

2023-06-05 06:51 UTC, kumagoro1202 approved these changes

2023-06-05 06:52 UTC, kumagoro1202 requested changes

2023-06-05 06:52 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +import nablarch.core.util.StringUtil;
使ってないimport

2023-06-05 06:57 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/web/HttpCookie.java
> +import nablarch.core.util.StringUtil;
削除しました。
合わせて、HttpCookieTestにも不要なimport文があったので削除しました。

2023-06-05 06:59 UTC, kumagoro1202 approved these changes

2023-06-05 06:59 UTC, merged