HttpRequest#getParam、getParamMapをアーキテクト向け公開APIに変更
nablarch/nablarch-fw-web pull request #128
Opened 2024-02-20 10:41 UTC by oguchi-shiori03

2024-02-27 08:06 UTC, kumagoro1202 requested changes

2024-02-27 08:06 UTC, kumagoro1202 commented on src/test/java/nablarch/common/util/WebRequestUtilTest.java
> +                    "----------------------------------------------------------------------------------------------------");
これはデバッグ用？

2024-02-27 09:08 UTC, oguchi-shiori03 commented on src/test/java/nablarch/common/util/WebRequestUtilTest.java
> +                    "----------------------------------------------------------------------------------------------------");
不要なコメントが残っていたので削除しました。

2024-02-28 01:45 UTC, kumagoro1202 approved these changes

2024-02-28 01:45 UTC, merged