Feature nab 355
nablarch/nablarch-fw-web pull request #70
Opened 2020-05-08 08:06 UTC by kiyohome

## 実装したもの

- CSRFトークンを生成する機能
- CSRFトークンをセッションストアへ保存する機能
- CSRFトークンを取得するAPI
- CSRFトークンを明示的にリフレッシュするAPI

## 未実装

- CSRFトークンを自動的に設定するJSPカスタムタグ

## 動作確認方法

- JUnitテスト

## その他、レビュアーへの申し送り事項など

主な機能は`CsrfTokenVerificationHandler`にあるので、そこから読んでもらうと良いと思います。

また、（アーキテクトではなく）アプリケーション開発者が利用できるクラスとして`CsrfTokenUtil`を用意しました。
このユーティリティではCSRFトークンの取得が行えます。
SPAとREST API構成の場合、CSRFトークンを取得できるエンドポイントを用意することがありますが、そのようなときに利用される想定です。
古くからあるサーバーサイドテンプレートエンジンを用いたアプリケーションであれば、テンプレートにCSRFトークンを埋め込むのが自然です。
便利のため、JSPカスタムタグの実装は必要だと思います。

2020-05-13 06:08 UTC, mseko commented on src/main/java/nablarch/fw/web/handler/csrf/VerificationFailureHandler.java
> +public interface VerificationFailureHandler {
アーキテクト向け公開にしていないことに何か理由はありますか？
検証失敗時の応答をカスタマイズ可能にするためにインターフェースにしたのだと思ったので、気になりました。

2020-05-13 06:13 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/csrf/VerificationFailureHandler.java
> +public interface VerificationFailureHandler {
漏れてました。追加しました！
https://github.com/nablarch/nablarch-fw-web/pull/70/commits/c19e0a6778cc76b230cb0fae27bd24b8d799d363

2020-05-13 06:19 UTC, mseko commented on src/main/java/nablarch/fw/web/handler/csrf/VerificationFailureHandler.java
> +public interface VerificationFailureHandler {
LGTM!

2020-05-14 00:32 UTC, backpaper0 requested changes
確認しました。

2020-05-14 00:32 UTC, backpaper0 commented on src/main/java/nablarch/common/web/csrf/CsrfTokenVerificationFailureException.java
> +public class CsrfTokenVerificationFailureException extends RuntimeException {
もう`CsrfTokenVerificationFailureException`は不要なので削除して良いと思います。

2020-05-14 00:41 UTC, kiyohome commented on src/main/java/nablarch/common/web/csrf/CsrfTokenVerificationFailureException.java
> +public class CsrfTokenVerificationFailureException extends RuntimeException {
削除しました！
https://github.com/nablarch/nablarch-fw-web/pull/70/commits/827360686d5d5826974dd978e083736cd4622c2a

2020-05-14 00:51 UTC, backpaper0 approved these changes
LGTM 👍

2020-05-14 02:32 UTC, merged