SecureHandlerでCache-Controlヘッダを付与できるように変更。
nablarch/nablarch-fw-web pull request #77
Opened 2020-08-14 05:10 UTC by kiyohome

https://nablarch.atlassian.net/browse/NAB-370
上記の対応です。

2020-08-17 09:20 UTC, backpaper0 requested changes

2020-08-17 09:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/handler/secure/CacheControlHeader.java
> + * 上書きは行わい。
typo!

2020-08-17 09:20 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/handler/secure/CacheControlHeader.java
> +        return !response.getHeaderMap().containsKey(getName());
`HttpResponse.getHeaderMap`は内部的に`HttpResponse.getContentType`を実行します。

[別件で書きましたが](https://github.com/nablarch/nablarch-fw-jaxrs/pull/12)、`HttpResponse.getContentType`は状態を変更する場合があります。

そのため、Nablarch内部では`HttpResponse.getContentType`および`HttpResponse.getContentType`を実行するメソッド（今回は`HttpResponse.getHeaderMap`）を使わない方が良いと思います。

2020-08-18 02:58 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/secure/CacheControlHeader.java
> + * 上書きは行わい。
対応しました！https://github.com/nablarch/nablarch-fw-web/pull/77/commits/1f8ab9de0108b6728b0d1ee55628870d5bffb84a

2020-08-18 02:59 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/secure/CacheControlHeader.java
> +        return !response.getHeaderMap().containsKey(getName());
対応しました！　https://github.com/nablarch/nablarch-fw-web/pull/77/commits/3825da8a619b3dc8d34821b7a08b36f7db977785

2020-08-18 05:02 UTC, backpaper0 approved these changes

2020-08-20 08:00 UTC, mseko commented
LGTM!

2020-08-20 08:00 UTC, merged