ヘルスチェックの仕組みを追加
nablarch/nablarch-fw-web pull request #80
Opened 2020-08-21 08:55 UTC by kiyohome

https://nablarch.atlassian.net/browse/NAB-378
上記に対応しました。

2020-08-26 04:57 UTC, backpaper0 requested changes

2020-08-26 04:57 UTC, backpaper0 commented on src/main/java/nablarch/fw/web/handler/health/DbHealthChecker.java
> +            connection.prepareStatement(dialect.getPingSql()).execute();
`PreparedStatement`は使い終わったら`close`しておいた方が行儀は良いと思いました（直後に`Connection`を`close`しているので実際には問題は起きないとは思いますが）。

2020-08-26 06:14 UTC, mseko commented
世古レビューしました。浦上さんの指摘対応が行なわれたら、マージ可です。

2020-08-26 07:18 UTC, backpaper0 commented
あ、すみません、もう一つだけありました。

```
    <dependency>
      <groupId>com.nablarch.framework</groupId>
      <artifactId>nablarch-core-jdbc</artifactId>
      <scope>provided</scope>
    </dependency>
```

これ`scope`は`compile`にして`<optional>true</optional>`の方が実態に即している気がしました。

`provided`は実行環境が用意する（例：サーブレットAPI）もの、`optional=true`はオプション、という感じなので。

2020-08-26 08:04 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/health/DbHealthChecker.java
> +            connection.prepareStatement(dialect.getPingSql()).execute();
closeしました！　https://github.com/nablarch/nablarch-fw-web/pull/80/commits/16e8d24903f14220de684545f187b06e3838abe3

2020-08-26 08:11 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/health/DbHealthChecker.java
> +            connection.prepareStatement(dialect.getPingSql()).execute();
closeするように変更しました！　https://github.com/nablarch/nablarch-fw-web/pull/80/commits/343d1bd59a5d2b1fd9f365dc81864ea946caa014

2020-08-28 02:11 UTC, mseko commented
LGTM!

2020-08-28 02:11 UTC, merged