デフォルトではContent-Typeの自動設定を行なわないように修正
nablarch/nablarch-fw-web pull request #92
Opened 2021-03-05 06:48 UTC by mseko

## 背景
https://nablarch.atlassian.net/jira/software/c/projects/NAB/issues/NAB-403

## やったこと
- nablarch.fw.web.HttpResponse#getContentType呼び出し時、デフォルト状態では `Content-Type` を自動で設定しないようにしました。
  nablarch.common.web.WebConfig#setSetContentTypeForResponseWithNoBody に値をtrue設定することで、 以前の動作に戻すことが出来ます。

## 確認したこと
- ユニットテストに成功すること

2021-03-05 08:30 UTC, kiyohome requested changes

2021-03-05 08:30 UTC, kiyohome commented on src/main/java/nablarch/common/web/WebConfig.java
> +    private boolean setContentTypeForResponseWithNoBody = false;
～するか否かの設定値は、他の場所でもこのような変数名にしてますか？

2021-03-05 08:30 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +     * webConfigコンポーネントのSetContentTypeForResponseWithNoBodyフラグがtrueかつ、
「webConfigコンポーネントのSetContentTypeForResponseWithNoBodyフラグがtrue」はJavadoc読んでもよく分からないのでは？

2021-03-05 08:30 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        WebConfig webConfig = WebConfigFinder.getWebConfig();
ソースの可読性が落ちてるので見直した方がいいです。
元のソースのif文に条件を足せばいいだけではないですか？
if (contentType == null && xxxxxxx()) {
xxxxxxx()はprivateでbooleanを返すイメージです。

2021-03-05 08:30 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +            if (contentType == null) {
空文字をmatcherに指定するのは変では？

2021-03-05 08:30 UTC, kiyohome commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> -        assertEquals("text/plain;charset=UTF-8", res.getContentType());
assertが消えてるのは何でですか？

2021-03-05 08:30 UTC, kiyohome commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> -        assertEquals("text/plain;charset=UTF-8", res.getContentType());
ここも。

2021-03-05 08:30 UTC, kiyohome commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        res.setHeader("Content-Type", null);
これは何のテストなんですかね？

2021-03-05 08:30 UTC, kiyohome commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        webConfig.setSetContentTypeForResponseWithNoBody(false);
デフォルトfalseなので、このテストは要りますか？

2021-03-05 08:30 UTC, kiyohome commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
>          res.setHeader("Content-Type", null);
res.setHeader("Content-Type", null); の呼び出しがよく分からないです。

2021-03-05 08:30 UTC, kiyohome commented on src/test/java/nablarch/fw/web/handler/SecureHandlerTest.java
> -                IsMapContaining.hasEntry("Content-Type", "text/plain;charset=UTF-8"),
これもアサートを消さない方がよくないですか？
これ後からテスト直してませんか？

2021-03-05 08:59 UTC, kumagoro1202 requested changes

2021-03-05 08:59 UTC, kumagoro1202 commented on src/main/java/nablarch/common/web/WebConfig.java
> +    private boolean setContentTypeForResponseWithNoBody = false;
getSet/setSetはさすがに見にくいのでneedsDefaultContentTypeForNoBodyResponseとかaddDefaultContentTypeForNoBodyResponseとかがいいんじゃないですかね。

2021-03-05 08:59 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +            if (contentType == null) {
ボディがある場合は新しい仕様でも今まで通りデフォルト値を設定するんですよね？
Content-Typeがnull イコール ボディが無いにはならないはずです。（コンテンツパス方式はイコールになりますが、直接ボディを書き込んだ場合Content-Typeは設定されていないけどボディはある状態が起こり得る）

2021-03-08 07:42 UTC, mseko commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> -        assertEquals("text/plain;charset=UTF-8", res.getContentType());
消したのはContent-Typeヘッダが無くなるためです。

しかし、HttpResponseクラスにプロパティは

2021-03-08 09:50 UTC, mseko commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> -        assertEquals("text/plain;charset=UTF-8", res.getContentType());
ここもHttpResponseクラスにプロパティは存在するため、assertします。

2021-03-08 09:51 UTC, mseko commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
>          res.setHeader("Content-Type", null);
Content-Typeを設定しなかった場合デフォルトでnullになるため、消します。

2021-03-08 09:52 UTC, mseko commented on src/test/java/nablarch/fw/web/handler/SecureHandlerTest.java
> -                IsMapContaining.hasEntry("Content-Type", "text/plain;charset=UTF-8"),
Content-Typeが無いことを確認するようにテストを修正しました。

2021-03-08 10:02 UTC, mseko commented on src/main/java/nablarch/common/web/WebConfig.java
> +    private boolean setContentTypeForResponseWithNoBody = false;
他の場所では、接尾辞にenabledを付けていたため変数名を変更しました。

2021-03-08 10:04 UTC, mseko commented on src/main/java/nablarch/common/web/WebConfig.java
> +    private boolean setContentTypeForResponseWithNoBody = false;
伊藤さんのレビュー指摘をうけて変数名を変更したため、getSet/setSetという命名を避けることが出来ました。

2021-03-08 10:13 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +     * webConfigコンポーネントのSetContentTypeForResponseWithNoBodyフラグがtrueかつ、
JavaDocを見直しました。

2021-03-08 10:13 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        WebConfig webConfig = WebConfigFinder.getWebConfig();
if文を見直しました。

2021-03-08 10:14 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +            if (contentType == null) {
ご指摘通り「Content-Typeがnull イコール ボディが無し」ではないため判定を追加しました。

2021-03-08 10:21 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +            if (contentType == null) {
contentTypeから文字列が取得できた場合にmatcherに指定するように修正しました。

2021-03-08 10:21 UTC, mseko commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        res.setHeader("Content-Type", null);
デフォルト値の場合のテストです。
こちらのテストを残して、明示的にfalseを指定した場合のテストを消しました。

2021-03-08 10:22 UTC, mseko commented on src/test/java/nablarch/fw/web/HttpResponseTest.java
> +        webConfig.setSetContentTypeForResponseWithNoBody(false);
不要です。消しました。

2021-03-09 00:54 UTC, kiyohome requested changes

2021-03-09 00:54 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +     * Content-Typeが設定されていない場合は、以下の振る舞いをする。<br />
「以下の振る舞いをする。」という表現は他のJavadocでよく使われてますか？

2021-03-09 00:54 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +     * ・システムリポジトリ中の{@link WebConfig#getContentTypeForResponseWithNoBodyEnabled()} がtrueの場合
「システムリポジトリ中の」は不要だと思います。

2021-03-09 00:54 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        if (contentType == null && (isContentTypeForResponseWithNoBody() || (getBodyString().length() != 0))) {
isBodyEmptyを使ってない理由はありますか？
クラスの中で整合が取れてないことになりませんか？

2021-03-09 00:54 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        if (contentType == null && (isContentTypeForResponseWithNoBody() || (getBodyString().length() != 0))) {
(isContentTypeForResponseWithNoBody() || (getBodyString().length() != 0))
Javadocは「かつ」となってますが分かりにくくないですか？
isContentTypeForResponseWithNoBody()がtrueとなったらボディの長さ見なくないですか？

2021-03-09 00:54 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +    private boolean isContentTypeForResponseWithNoBody(){
WebConfigのプロパティ名と合わせてない理由はありますか？
レスポンスボディを持たないコンテンツタイプかどうか？となりませんか？

2021-03-09 00:54 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +            charset = UTF_8;
素直にif/elseで書いた方が分かりやすくないですか？
contenttypeが設定されていれば抜き出して、設定されてなければデフォルトでUTF-8にしてるんですよね？

2021-03-09 01:28 UTC, mseko commented on src/main/java/nablarch/common/web/WebConfig.java
> +    private boolean setContentTypeForResponseWithNoBody = false;
変数名をaddDefaultContentTypeForNoBodyResponseに改めました。

2021-03-09 01:33 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +     * Content-Typeが設定されていない場合は、以下の振る舞いをする。<br />
「振る舞いをする」はあまり使われない表現であるため、「処理を行う」に表現を改めました。

2021-03-09 01:34 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +     * ・システムリポジトリ中の{@link WebConfig#getContentTypeForResponseWithNoBodyEnabled()} がtrueの場合
「システムリポジトリ中の」を取り除きました。

2021-03-09 01:36 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +    private boolean isContentTypeForResponseWithNoBody(){
WebConfigのプロパティ名と合わせたほうが分かりやすいため合わせました。

2021-03-09 02:33 UTC, kumagoro1202 requested changes

2021-03-09 02:33 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/handler/HttpResponseHandler.java
> +            ctx.getServletResponse().setContentType(res.getContentType());
contentTypeを取り直す意味はありますか。

2021-03-09 03:24 UTC, mseko commented on src/main/java/nablarch/fw/web/handler/HttpResponseHandler.java
> +            ctx.getServletResponse().setContentType(res.getContentType());
取り直す意味はありません。
取得済みのcontentTypeを使用するように修正しました。

2021-03-09 04:05 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        if (contentType == null && (isContentTypeForResponseWithNoBody() || (getBodyString().length() != 0))) {
JavaDocと条件式を見直しました。

2021-03-09 04:06 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +            charset = UTF_8;
素直なif/elseに書き直しました。

2021-03-09 04:48 UTC, kumagoro1202 requested changes

2021-03-09 04:48 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +    private boolean isSetDefaultContentType() {
isSetよりneedsとかの方がいいかと思います。

2021-03-09 04:56 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +    private boolean isSetDefaultContentType() {
needsDefaultContentTypeにメソッド名を改めました。

2021-03-09 04:57 UTC, kumagoro1202 approved these changes

2021-03-09 05:20 UTC, kiyohome requested changes

2021-03-09 05:20 UTC, kiyohome commented on src/main/java/nablarch/fw/web/ResponseBody.java
> +        if(contentPath != null || input !=null || tempFile != null){
isEmptyを修正してますが後方互換への影響はないでしょうか？

2021-03-09 05:20 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +                } else {
if (contentType != null) {
 ・・・
}
if (contentType == null) {
    contentType = UTF_8;
}
とすればUTF-8は1回でよくないですか？
}

2021-03-09 06:23 UTC, mseko commented on src/main/java/nablarch/fw/web/ResponseBody.java
> +        if(contentPath != null || input !=null || tempFile != null){
再度確認したところ、レアケースでHttpErrorHandlerに影響がありましたので、isEmptyの修正を取りやめました。

2021-03-09 06:23 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +                } else {
指摘を取り込みました。

2021-03-09 06:32 UTC, kiyohome requested changes

2021-03-09 06:32 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        return WebConfigFinder.getWebConfig().getAddDefaultContentTypeForNoBodyResponse() || !body.isEmptyOrBufferZeo();
isEmptyOrBufferZeoメソッド追加の判断が分からないです。
このメソッド追加が一番よい対応方法なのでしょうか？

2021-03-09 06:45 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        return WebConfigFinder.getWebConfig().getAddDefaultContentTypeForNoBodyResponse() || !body.isEmptyOrBufferZeo();
実装時に以下を候補として考えました。

1. isBodyEmpty()を使用する。  
   →この方法は、ボディが空でも「ボディが存在する」と判断されるケースがあるため採用できず。
      また、仕様変更を行うと既存の処理への影響があるため、処理の変更は不可能。
2.  既存のメソッドであるResponseBody#toString() を使用する。
   → 目的を満たすことは可能ですが、「ストリームから読み出す」という不要な処理を行っておりベストな実装とは言えません。
3.  ResponseBodyに新しくメソッドを作成する(今回採用した方法)
  → 今回の目的に即したメソッドを実装できる。またResponseBodyは非公開クラスであるため、公開APIの不要な追加はない。

2021-03-09 06:57 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        return WebConfigFinder.getWebConfig().getAddDefaultContentTypeForNoBodyResponse() || !body.isEmptyOrBufferZeo();
1の既存処理への影響とありますが、isBodyEmptyの変更影響を十分に検討できていますか？既存システムに実害がある影響がありますか？
2はないと思います。
3だとしてResponseBodyへのメソッド追加が一番良い解決策ですか？HttpResponseに追加してないのはなぜですか？そもそも、isEmptyで解釈が2つあるのは整合性が取れてなく、今後のメンテに影響しませんか？

2021-03-15 00:15 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        return WebConfigFinder.getWebConfig().getAddDefaultContentTypeForNoBodyResponse() || !body.isEmptyOrBufferZeo();
HttpResponseHandler#writeResponse()の実装を変更することで、HttpResponseへの「ボディが空か否か」のメソッドの追加が不要であることが分かり、HttpResponseへのメソッド追加を止めました。

HttpResponseHandler#writeResponse()にて、HttpResponse#getBodyStream()の呼び出し前にwriteHeaders()を呼び出すことでヘッダ書き込みを行うことで、HttpResponseに空のバッファを作る前に「ボディが空か否か」の判定処理を行えます。
このため、既存のHttpResponse#isEmpty()メソッドを使用した判定が可能になります。
https://github.com/nablarch/nablarch-fw-web/blob/66095fe6e3ee69e1872998eb756ee93691385d3b/src/main/java/nablarch/fw/web/handler/HttpResponseHandler.java#L259

2021-03-15 05:59 UTC, mseko commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        return WebConfigFinder.getWebConfig().getAddDefaultContentTypeForNoBodyResponse() || !body.isEmptyOrBufferZeo();
ResponseBody#isEmpty()の実装する案を採用しました。

懸念していた既存の処理への影響ですが、実質的に問題ないことが確認できました。  
HttpErrorHandler及びHttpMessagingErrorHandlerが空のレスポンスを返せなくなるケースを懸念していました。  
ウェブアプリケーション及びHTTPメッセージングの基盤でRESTFulな応答を返すActionを実装した場合に、ボディが空の応答を返せなくなるケースがあるというものでした。  
これが発生するのはHttpErrorHandler及びHttpMessagingErrorHandlerに対して、コンポーネント定義ファイルで、ステータスコードデフォルトの応答を明示的に定義した場合です。  
意図的に空の応答を返したい場合は、通常204等特定のステータスコードのみです。空の応答を返したいステータスコードにデフォルトの応答を定義するとは考えにくいため、実質的に問題ありません。

2021-03-15 07:25 UTC, kiyohome requested changes

2021-03-15 07:25 UTC, kiyohome commented on src/main/java/nablarch/fw/web/ResponseBody.java
> +        if(buffer != null && buffer.position() > 0){
return buffer == null || buffer.position() <= 0
でよくないですか？

2021-03-15 07:25 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/HttpResponseHandler.java
> +                writeHeaders(res, ctx);
呼び出し順を変えてますが影響ないでしょうか？
writeHeadersでflushしてるので気になりました。

2021-03-15 08:26 UTC, mseko commented on src/main/java/nablarch/fw/web/ResponseBody.java
> +        if(buffer != null && buffer.position() > 0){
対応しました。

2021-03-15 08:29 UTC, mseko commented on src/main/java/nablarch/fw/web/handler/HttpResponseHandler.java
> +                writeHeaders(res, ctx);
影響ないです。  
259行目のwriteHeaders()の呼び出し後ステータスコード及びヘッダの再設定はないため、呼び出し順変更前とクライアントへのレスポンスが変わることはありません。

2021-03-15 08:56 UTC, kiyohome requested changes

2021-03-15 08:56 UTC, kiyohome commented on src/main/java/nablarch/fw/web/handler/HttpResponseHandler.java
> +                writeHeaders(res, ctx);
順番を変えた処理部分で実行時例外が発生すると、フラッシュしたヘッダーだけ先にブラウザに返されることになりませんか？

2021-03-15 08:56 UTC, kiyohome commented on src/main/java/nablarch/fw/web/HttpResponse.java
> +        return WebConfigFinder.getWebConfig().getAddDefaultContentTypeForNoBodyResponse() || !body.isEmptyOrBufferZeo();
他のとこでフィードバックしているのでここはクローズします。

2021-03-16 06:23 UTC, kumagoro1202 requested changes

2021-03-16 06:23 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/web/handler/HttpResponseHandlerTest.java
> +        //------------------ writeのパターン ------------- //
このコメントどういう意味ですか。

2021-03-16 06:32 UTC, mseko commented on src/test/java/nablarch/fw/web/handler/HttpResponseHandlerTest.java
> +        //------------------ writeのパターン ------------- //
不要なコメントですので、削除しました。

2021-03-16 06:34 UTC, merged