feat: HTTPアクセスログをJSON書式で出力する機能の追加
nablarch/nablarch-fw-web pull request #94
Opened 2021-03-09 02:00 UTC by shuji-k

・HttpAccessJsonLogFormatterクラスの追加（HTTPアクセスログのJSON実装）
・HttpAccessLogFormatterクラスの修正（継承して使用するための修正）

2021-03-22 07:02 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessLogFormatter.java
> +     * 設定情報各ログ出力が有効か否かを初期化する。
設定情報各ログ出力？

2021-03-22 07:02 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessLogFormatter.java
> +     * コンストラクタ。
この修正は必要でしょうか？

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +import static org.hamcrest.Matchers.*;
importは省略せずに。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        System.clearProperty("httpAccessLogFormatter.maskingPatterns");
`LogTestSupport` を継承しているので、システムプロパティのクリアは不要。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +//        System.setProperty("httpAccessLogFormatter.parametersOutputEnabled", "false");
不要なコメントは削除。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        assertThat(message.substring(6), isJson(allOf(
`"$JSON$".length()` の方が意図が伝わりやすいかなと思いました。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        HttpAccessLogFormatter.HttpAccessLogContext logContext = createLogContext();
様々なテストで使用する設定が `createLogContext()` にまとめられているせいで、テストが読みづらく、また保守もしづらい状態になっているように思えました。

`assertThat()` で検証している値が `HttpAccessLogContext` のどこに設定された値に対応しているのか確認しようとすると、テストメソッドと `createLogContext()` を何度も往復しなければならず、読みづらいと思いました。

また、現在の `createLogContext()` は、「あるテストケース用の設定処理」と「別のテストケース用の設定処理」とがごちゃまぜになっている状態なので、「`createLogContext()` 内のどの処理がどこのテストケースのために書かれているのか」が分かりにくくなっています。
このため、 `createLogContext()` 内のあるコードを修正したときに、どこのテストケースに影響が出るのかが判断しづらくなってしまい、修正がしづらい（保守がしづらい）テストコードになってしまっていると思います。


`createLogContext()` には、以下のいずれかの処理だけを含めるようにした方がいいと思います。

- 本当に全てのテストケースで共通で必要になる処理
    - （たいてい、そういうのは事前処理になるので、 `@Before` メソッドに移動しそうですが）
- テストメソッド内で書くとノイズになってテストコードが読みづらくなる処理
    - 今回だと、 `MockServletRequest` や `ServletExecutionContext` を生成してセットするような処理は、テストコード内に書いてるとノイズになりそうです

そして、個別のテストケースで必要になる検証値の設定は、個々のテストメソッド内で実装するのがいいと思います。

実装イメージ

```java

    /**
     * {@link HttpAccessJsonLogFormatter#formatParameters}メソッドのテスト。
     */
    @Test
    public void testFormatParameters() {
        System.setProperty("httpAccessLogFormatter.beginOutputEnabled", "false");
        System.setProperty("httpAccessLogFormatter.dispatchingClassOutputEnabled", "false");
        System.setProperty("httpAccessLogFormatter.endOutputEnabled", "false");
        System.setProperty("httpAccessLogFormatter.maskingPatterns", "req_param2");

        HttpAccessLogFormatter formatter = new HttpAccessJsonLogFormatter();

        HttpAccessLogFormatter.HttpAccessLogContext logContext = createEmptyLogContext();
        logContext.getParameters().put("req_param1", new String[] {"req_param1_test"});
        logContext.getParameters().put("req_param2", new String[] {"must be masked"});
        logContext.getParameters().put("req_param3", new String[] {"req_param3_test"});

        ThreadContext.setRequestId("request_id_test");
        ThreadContext.setUserId("user_id_test");

        String message = formatter.formatParameters(logContext);
        assertThat(message.startsWith("$JSON$"), is(true));
        assertThat(message.substring(6), isJson(allOf(
                withJsonPath("$.parameters.req_param1", hasSize(1)),
                withJsonPath("$.parameters.req_param1[0]", equalTo("req_param1_test")),
                withJsonPath("$.parameters.req_param2", hasSize(1)),
                withJsonPath("$.parameters.req_param2[0]", equalTo("*****")),
                withJsonPath("$.parameters.req_param3", hasSize(1)),
                withJsonPath("$.parameters.req_param3[0]", equalTo("req_param3_test")))));
    }

    private HttpAccessLogFormatter.HttpAccessLogContext createEmptyLogContext() {
        MockServletRequest servletReq = new MockServletRequest();
        servletReq.setSession(new MockHttpSession());
        ServletExecutionContext servletExecutionContext = new ServletExecutionContext(servletReq, null, null);

        HttpAccessLogFormatter.HttpAccessLogContext logContext = new HttpAccessLogFormatter.HttpAccessLogContext();
        logContext.setContext(servletExecutionContext);
        logContext.setRequest(servletExecutionContext.getHttpRequest());

        return logContext;
    }
```

修正後の `testFormatParameters()` なら、そのテストケースの前提条件と期待する結果が同じメソッド内に収まるので、何度もスクロールする必要もなくなり読みやすくなったと思います。

また、修正前だと `createLogContext()` 内のどの設定が `testFormatParameters()` に影響を与えるのかわかりづらかったですが、修正後なら `testFormatParameters()` が関係しているのは `getParameters()` で設定している情報だけ、というのがハッキリしていると思います。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        logContext.setStartTime(1614767032553l);
`1614767032553` ミリ秒 が `2021-03-03 19:23:52.553` であると認識するのは、人間にはちょっと難しいです。

ひと手間必要ですが、次のようなメソッドを用意することで人間にも読みやすくなると思います。

```java
        logContext.setStartTime(toMilliseconds("2021-03-03 19:23:52.553"));
...
    private long toMilliseconds(String textDate) throws Exception {
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").parse(textDate).getTime();
    }
```

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +     * {@link HttpAccessJsonLogFormatter#formatEnd}メソッドのテスト。
説明が `testFormatEnd()` と同じです。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +     * {@link HttpAccessJsonLogFormatter#formatEnd}メソッドのテスト。
説明が `testFormatEnd()` と同じです。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +    private HttpAccessLogFormatter.HttpAccessLogContext createLogContextNoResStCd() {
このメソッドは使われていないようなので削除してください。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +    public void testFormatEndWithTargets() {
[SqlJsonLogFormatterTest の指摘](https://github.com/nablarch/nablarch-core-jdbc/pull/54#discussion_r595789148)と同じで、他の出力メソッドでのテストケースが必要です。

2021-03-22 07:02 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +            // (coverage) statusCodeが-1となるケースはない
↓こんな実装を用意すれば、一応 `-1` を実現できますね。

```java
        logContext.setResponse(new HttpResponse() {
            @Override
            public int getStatusCode() {
                return -1;
            }
        });
```

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +                withJsonPath("$", hasEntry("responseStatusCode", 200)))));
`statusCode` のエントリが無いことの確認もあった方がいいのではと思いました。

2021-03-22 07:02 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +        containsMemoryItem = false;
`boolean` のインスタンス変数はデフォルト `false` で初期化されるので、この記述は要らないと思います。

2021-03-22 07:02 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        assertThat(formatter.containsMemoryItem(), is(true));
`containsMemoryItem` の制御の確認が他のテストの「ついで」になっていて、テストコードを見ただけでは「どういう条件のときに `true` となるべきか」が全く読み取れません。

別途テストケースを分けて、～～のときに `true` となること、と仕様が明確に分かるようにした方がいいと思います。

2021-03-22 07:15 UTC, shuji-k commented on src/main/java/nablarch/fw/web/handler/HttpAccessLogFormatter.java
> +     * 設定情報各ログ出力が有効か否かを初期化する。
(対応待ち)

2021-03-22 07:15 UTC, shuji-k commented on src/main/java/nablarch/fw/web/handler/HttpAccessLogFormatter.java
> +     * コンストラクタ。
(対応待ち)

2021-03-22 07:15 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +import static org.hamcrest.Matchers.*;
(対応待ち)

2021-03-22 07:15 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        System.clearProperty("httpAccessLogFormatter.maskingPatterns");
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +//        System.setProperty("httpAccessLogFormatter.parametersOutputEnabled", "false");
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        assertThat(message.substring(6), isJson(allOf(
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        HttpAccessLogFormatter.HttpAccessLogContext logContext = createLogContext();
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        logContext.setStartTime(1614767032553l);
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +     * {@link HttpAccessJsonLogFormatter#formatEnd}メソッドのテスト。
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +     * {@link HttpAccessJsonLogFormatter#formatEnd}メソッドのテスト。
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +    private HttpAccessLogFormatter.HttpAccessLogContext createLogContextNoResStCd() {
(対応待ち)

2021-03-22 07:16 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +    public void testFormatEndWithTargets() {
(対応待ち)

2021-03-22 07:17 UTC, shuji-k commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +            // (coverage) statusCodeが-1となるケースはない
(対応待ち)

2021-03-22 07:17 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +                withJsonPath("$", hasEntry("responseStatusCode", 200)))));
(対応待ち)

2021-03-22 07:17 UTC, shuji-k commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +        containsMemoryItem = false;
(対応待ち)

2021-03-22 07:17 UTC, shuji-k commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        assertThat(formatter.containsMemoryItem(), is(true));
(対応待ち)

2021-03-31 10:10 UTC, shuji-k commented
下記メッセージログでご指摘頂いた内容について、本クラスも対象と考え、以下で対応しました。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/f24278eda552f56f06ae7a3b1390e64733f5511c

2021-03-31 10:11 UTC, shuji-k commented
Overrideアノテーションの対応漏れがありましたので、以下で対応しました。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/4cfa632bd485d611020fd4801cb4ad48aeee09f4

2021-04-05 00:13 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessLogFormatter.java
> +     * コンストラクタ。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/0445539e07139e09cbe515f5dcf3f979c4915f4b
元に戻した。

2021-04-05 00:16 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +import static org.hamcrest.Matchers.*;
https://github.com/nablarch/nablarch-fw-web/commit/21f98319d322fedd6e6dcdb46975251abf928c69#diff-a1868cee8468d82c19678d649a4434e1323be52d98baa3fdf5364459e3f4f3bf
https://github.com/nablarch/nablarch-fw-web/commit/f24278eda552f56f06ae7a3b1390e64733f5511c#diff-a1868cee8468d82c19678d649a4434e1323be52d98baa3fdf5364459e3f4f3bf

上記２つで対応されてた。

2021-04-05 01:08 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        logContext.setStartTime(1614767032553l);
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/ae28b7a191de4654de006b1bebbd13cc9f502fa1

2021-04-05 01:16 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +     * {@link HttpAccessJsonLogFormatter#formatEnd}メソッドのテスト。
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/6236fd1d78407a0b958116c2176593a7fb7180d4

2021-04-05 01:17 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +     * {@link HttpAccessJsonLogFormatter#formatEnd}メソッドのテスト。
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/6236fd1d78407a0b958116c2176593a7fb7180d4

2021-04-05 02:13 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        HttpAccessLogFormatter.HttpAccessLogContext logContext = createLogContext();
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/f51bcc2566085a914ddfcc442c1ac8f204e4e036

2021-04-05 02:52 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +    public void testFormatEndWithTargets() {
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/830f869710d22c3ceed0373f843043c2301eb02f

2021-04-05 02:57 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        System.setProperty("httpAccessLogFormatter.maskingPatterns", "req_param2");
`formatParameters()` をテストするときに他のフォーマットメソッド(`formatBegin()` や `formatEnd`)を無効にしていますが、わざわざ無効にする必要はないのでは、と思いました。

他のフォーマットメソッドの有効・無効が `formatParameters()` に影響を与えるとは思えないですし、仮に影響があるなら有効の場合と無効の場合のテストケースがそれぞれ必要になるはずです。

これ以外のフォーマットメソッドのテストも、同じように他のフォーマットメソッドを無効化していますが、必要ないのではと思いました。

2021-04-05 04:44 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +            // (coverage) statusCodeが-1となるケースはない
以下で対応
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/ebf4ae5a424500430776ee7a8b8903847cc01d16

2021-04-05 04:47 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +                withJsonPath("$", hasEntry("responseStatusCode", 200)))));
以下で対応
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/646ba39a08d6ee9a1a365ac576469a9cdea65b8d

ついでに、メソッド名が `WithNoStatusCode` を `WithoutStatusCode` に修正（こっちの方が自然かと思ったので）。

2021-04-05 04:48 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +        containsMemoryItem = false;
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/8d9360386a7de342660b5d7177495633b5912357

2021-04-05 07:10 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        System.setProperty("httpAccessLogFormatter.maskingPatterns", "req_param2");
以下で対応
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/286bcbec9445f21aa335fd88de84b3dbec0e5690

2021-04-06 02:27 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        System.clearProperty("httpAccessLogFormatter.maskingPatterns");
訂正。

`LogTestSupport` はシステムプロパティのロールバックをしていない。

[nablarch-core-applog の LogTestSupport](https://github.com/nablarch/nablarch-core-applog/blob/1.2.0/src/test/java/nablarch/core/log/LogTestSupport.java#L55) がシステムプロパティのロールバックをしており、同名のクラスが他のプロジェクトにも存在したため、同じようにロールバックが行われているモノと勘違いしていた。
実際は、プロジェクトによってロールバックの有無が異なっている。

したがって、システムプロパティのロールバックは必要。

以下で修正。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/dfba63079f4d880851e789dd6da7f83fbff5cf43

※nablarch-test-supportに[システムプロパティをクリーンアップするルールを追加](https://github.com/nablarch/nablarch-test-support/pull/20)して、それを利用するように修正。

2021-04-06 07:56 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +    private static class LabelBuilder implements JsonLogObjectBuilder<HttpAccessLogContext> {
各出力項目制御クラスは `public` で宣言する。

2021-04-06 08:01 UTC, opengl-8080 commented on src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java
> +    private static class LabelBuilder implements JsonLogObjectBuilder<HttpAccessLogContext> {
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/15a2fb8028c408eea6bc287f5539a50529f1f34d

2021-11-15 05:51 UTC, opengl-8080 commented
refs: https://github.com/nablarch/nablarch-fw-web/pull/94#issuecomment-810947757

ラベルの値を明示した場合のテストケースを追加。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/5b01cd227ab1fde5a5c96ac70ad9b9d57787e5f6

2021-11-15 07:22 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        assertThat(formatter.containsMemoryItem(), is(true));
追加指摘

[HttpAccessLogFormatterの実装](https://github.com/nablarch/nablarch-fw-web/blob/master/src/main/java/nablarch/fw/web/handler/HttpAccessLogFormatter.java#L184) を見ると、 `containsMemoryItem` は終了ログでメモリの出力が指定されている場合のみ true が設定されるものになっている。

しかし、 [HttpAcessJsonLogFormatterでは](https://github.com/nablarch/nablarch-fw-web/blob/feature-NAB-392/src/main/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatter.java#L233)全てのログ出力のターゲットで true の設定を制御するようになってしまっていて、動きが異なる。

2021-11-15 07:36 UTC, opengl-8080 commented
`HttpAccessJsonLogFormatter` の各フォーマットが無効だった場合のテストケースが漏れている（カバレッジが不足している）。

2021-11-15 07:37 UTC, opengl-8080 requested changes

2021-11-15 07:37 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +public class HttpAccessJsonLogFormatterTest extends LogTestSupport {
`HttpAccessJsonLogFormatter` の各フォーマットが無効だった場合のテストケースが漏れている（カバレッジが不足している）。

2021-11-15 08:01 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +        assertThat(formatter.containsMemoryItem(), is(true));
以下で対応。
https://github.com/nablarch/nablarch-fw-web/pull/94/commits/6a3b29211b8c09e8ae5c6d2401cde8967c217b50

2021-11-16 04:45 UTC, opengl-8080 commented on src/test/java/nablarch/fw/web/handler/HttpAccessJsonLogFormatterTest.java
> +public class HttpAccessJsonLogFormatterTest extends LogTestSupport {
以下で対応

https://github.com/nablarch/nablarch-fw-web/pull/94/commits/d5bb90282107a090556e92f5b753aac0378ab3c9

2021-12-09 07:44 UTC, opengl-8080 approved these changes

2021-12-09 07:45 UTC, merged